# Generated by Django 4.2.3 on 2023-07-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=30)),
                ('avatar', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
