# Generated by Django 4.2.3 on 2023-08-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_back', '0002_alter_users_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
