# Generated by Django 4.2.3 on 2023-08-21 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_back', '0003_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=80)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
