# Generated by Django 4.2.3 on 2023-08-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_back', '0005_product_user_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_product',
            old_name='name',
            new_name='name_product',
        ),
        migrations.RenameField(
            model_name='user_product',
            old_name='user_id',
            new_name='user',
        ),
    ]
