# Generated by Django 4.2.3 on 2023-08-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_back', '0006_rename_name_user_product_name_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_product',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='food_back.product', verbose_name='Эталонный продукт'),
        ),
    ]
