# Generated by Django 4.2.3 on 2023-08-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_back', '0007_alter_user_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='user_product',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='products', to='food_back.product', verbose_name='Эталонный продукт'),
        ),
    ]
