# Generated by Django 4.2.3 on 2023-08-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_back', '0008_remove_user_product_product_id_user_product_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_product',
            name='product',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='food_back.product', verbose_name='Эталонный продукт'),
        ),
    ]
