# Generated by Django 4.2.3 on 2023-09-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_back', '0009_alter_user_product_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('product_number', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=models.SET(None), to='food_back.category', verbose_name='Категория')),
                ('product', models.ManyToManyField(to='food_back.product', verbose_name='Эталонный продукт')),
            ],
        ),
    ]
