# Generated by Django 4.2.3 on 2023-09-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_back', '0010_category_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_user',
            name='favorite_recipe',
            field=models.ManyToManyField(to='food_back.recipe'),
        ),
    ]
